### ISSUE TITLE
Include song information on page title/m3u

### ISSUE THREAD

**Issue by cha0sbuster** [bemusic/bmsurge#2]
I'm running the .m3u via VLC Music Player, and the one thing that bugs me is that I have to have the site open in the tab in order to see what's playing. Is it possible that the Artist/Title/Event information could be put on the title of the tab and/or broadcasted to the .m3u file so that it shows up in VLC/other internet radio players?

**Comment by cha0sbuster** [comment]
Oh! Hmm. Lemme see what other players I have installed will work properly.
(I'm specifically looking for player metadata, because I'm a streamer and I wanted to use Surge as background music, so if there's a way to get it working so SMG Now Playing can pick it up, I wanna do that.)

**Comment by cha0sbuster** [comment]
Update: Foobar2000 works fine with it!

**Comment by dtinth** [comment]
@cha0sbuster So happy to hear that you’d like to use bmsurge as a background music for your stream!

**Comment by dtinth** [comment]
An option to display current song on the page title is now available :D

**Comment by cha0sbuster** [comment]
Could the event be parsed as an album, and the theme as its genre, by any chance? Would help with organization a bit.

**Comment by dtinth** [comment]
@cha0sbuster Unfortunately the streaming format we use only support Artist and Title. I also took a look at SMG Now Playing chrome extension, but didn’t find a way to integrate with it, since their site list is fixed (hardcoded).

However, if you use OBS, you can use this webpage to display the current song with BrowserSource.

https://bmsurge-music-request.glitch.me/streamer.html

You can customize the colors, font, etc. with custom CSS. Here’s an example configuration:

<img width="832" alt="image" src="https://user-images.githubusercontent.com/193136/65460125-706c4c00-de7b-11e9-8033-9eac11ca188c.png">

**Comment by cha0sbuster** [comment]
Oh, that's excellent! Thank you.
